export const SECTIONS = [
  { key: 'junior', label: 'Junior Student', emoji: '🧒', color: '#1F4E78', awards: [
    'Junior Class Prefect of the Year',
    'Most Talented Junior Student (Female)',
    'Most Talented Junior Student (Male)',
    'Most Popular Junior Student (Female)',
    'Most Popular Junior Student (Male)',
    'Most Influential Junior Student of the Year',
    'Junior Peer Mentor of the Year',
    'Most Punctual Student of the Year (Junior)',
  ]},
  { key: 'senior', label: 'Senior Student', emoji: '🎓', color: '#5B2E91', awards: [
    'Media Personality of the Year',
    'Fattest Wallet (D-Bee) of the Year',
    'Most Hardworking Class Prefect of the Year',
    'Most Hardworking Prefect of the Year',
    'Most Influential Student of the Year',
    'Most Talented Student of the Year',
    'Most Fashionable Student (Female)',
    'Most Fashionable Student (Male)',
    'Most Photogenic Student (Female)',
    'Most Photogenic Student (Male)',
    'Fine Girl of the Year',
    'Fine Boy of the Year',
    'Most Popular Student (Female)',
    'Most Popular Student (Male)',
    'Senior Peer Mentor of the Year',
    'Most Punctual Student of the Year (Senior)',
    'Lady of the Year',
    'Gentleman of the Year',
    'Best Student Personality of the Year',
  ]},
  { key: 'open', label: 'Open Category (Junior & Senior)', emoji: '🤝', color: '#B3891F', awards: [
    'Best Debater of the Year',
    'Most Hilarious Student of the Year',
    'Future Icon (Most Likely to Blow) of the Year',
    'Heart of Gold (Kindest Student) of the Year',
    'Most Eloquent Student of the Year',
  ]},
  { key: 'staff', label: 'Teaching Staff', emoji: '🏅', color: '#7A1F3D', awards: [
    'Most Punctual Teacher of the Year',
    'Form Master/Mistress of the Year',
    'No-Nonsense Teacher (Disciplinarian) of the Year',
    'Most Feeling Teacher of the Year',
    'Most Popular Teacher of the Year',
    'House Master/Mistress of the Year',
  ]},
  { key: 'others', label: 'Others', emoji: '🏫', color: '#0F5132', awards: [
    'Campus Club of the Year',
    'Department of the Year',
    'Best Pals of the Year',
    'Best House of the Year',
  ]},
];

export const TOTAL_AWARDS = SECTIONS.reduce((sum, s) => sum + s.awards.length, 0);
